### ISSUE TITLE
Custom RC with switches only

### ISSUE THREAD

**Issue by not7cd** [kkbin505/Arduino-Transmitter-for-ELRS#10]
Hey, I was building a custom case with only switches and used your code as a library. I have some issues sending the actual commands and setting a proper Packet Rate. 

Here are the specs of our project:
* Arduino MEGA, the source code shares process time with ethernet connection and MQTT messages.
* We are using Nano module, I had no luck with JR micro module
* ExpressLRS 3.2.1. Which version did you use?
* I have set different Packet Rate

What is happening:
* Handset detected by Nano TX Module
* Connects to RX module
* No inputs visible on the flight controller side

Maybe you have some ways to debug this, as 
Our source code: https://gitlab.com/SimLE/simba/control-panel-software

I would be grateful if you could help soon.

**Comment by MattiasKallio** [comment]
Hi!

I'm not sure why I got this message, I am not involved in that project at
all.

But it's weirdly close to things I do, so I had to go through some code to
be sure. 😂



Cheers
//Mattias

Den ons 14 juni 2023 22:07Norbert Szulc ***@***.***> skrev:

**Comment by kkbin505** [comment]
Did you make it?

**Comment by ne9n** [comment]
no not yet.  It is on deck for a winter project.
I have several never used old RC transmitters I would like to convert to a
new encoder and RF deck.  I wanted to use 50 Mhz as I am a ham but saw ELRS
and am looking at it.

I am an EE manager and my day job is very close to this so, it will be a
fun project.

**Comment by kkbin505** [comment]
This is a discussion more than an issue. I suggest moveing to elrs discord for further discussion.
