### ISSUE TITLE
Adding channels

### ISSUE THREAD

**Issue by ArshaanTech** [kkbin505/Arduino-Transmitter-for-ELRS#12]
This supports upto 12 channels ryt? I was wondering how to add up to 8 analog inputs as channels... other than 4 for joysticks.

**Comment by longlong7211** [comment]
I think you can add it yourself in the code. It's not too difficult to find the code to add a few channels. The author's PCB has no space left so I think he doesn't support adding channels, but that code is ready for adding some channels

**Comment by ArshaanTech** [comment]
Oh okay thanks.
