### ISSUE TITLE
Support for Un-Inverted CRSF

### ISSUE THREAD

**Issue by inx199** [kkbin505/Arduino-Transmitter-for-ELRS#13]
Iam using custom build firmware on my R9M, and i cant change the UART_INVERTED option, I know arduino can't output Un-inverted CRSF, but can it be done via hardware that can simply inverse the signal? or by using ESP32 which support signal inversion?

**Comment by sercona** [comment]
yes, the simplest solution is to use a logic gate and literally invert the uart signal.  note you may need 3.3v logic (likely so).

**Comment by kkbin505** [comment]
> Iam using custom build firmware on my R9M, and i cant change the UART_INVERTED option, I know arduino can't output Un-inverted CRSF, but can it be done via hardware that can simply inverse the signal? or by using ESP32 which support signal inversion?

For arduino based simple TX, you need a logical invert gate to do that.
If you need to implement uart-inverted in the TX side, my suggestion is to use ESP32 based simple TX instead which have build inverted uart option.
https://github.com/danxdz/simpleTx_esp32
