### ISSUE TITLE
ELRS external antenna

### ISSUE THREAD

**Issue by slovigr** [kkbin505/Arduino-Transmitter-for-ELRS#14]
Hello,

I am working on the possibility to create an external antenna for ELRS TX module.

Your project is very interesting and I have some questions about it.

Is it possible to discuss my questions by mail, or some messenger?

Thank you in advance.

**Comment by kkbin505** [comment]
> Hello,
> 
> I am working on the possibility to create an external antenna for ELRS TX module.
> 
> Your project is very interesting and I have some questions about it.
> 
> Is it possible to discuss my questions by mail, or some messenger?
> 
> Thank you in advance.

For ELRX TX module discusstion, I suggest to move to ELRS discord, there are more active discussion and more people can help you. Thanks
