### ISSUE TITLE
digital buttons doesnt work

### ISSUE THREAD

**Issue by womihako** [kkbin505/Arduino-Transmitter-for-ELRS#16]
Hi, this is a nice project and i did it.
So i have connection to the Flight controllor and also can see the analog inputs.
but the switches doesnt work. maybe can get some help?

**Comment by sercona** [comment]
are you sure you have the right gpio numbers?  and you are using switches to connect those to ground?

I have 4 switches working; 2 2-pos and 2 3-pos and they all work ok.  you have to check the code to make sure that all your switches have code that runs (not commented out, etc).

**Comment by kkbin505** [comment]
How did you connect the switch. For 2-pos switch, it should be connect 1 pin to the one of the digital pin you declared and the other pin to ground. The digital should be pull up in the setup section. The digital read is high unless you use switch to "ground" it.

**Comment by kkbin505** [comment]
This is not a software issue, it may be related to some wiring issue. Please check your diagram.
