### ISSUE TITLE
请问怎么能支持ESP32?

### ISSUE THREAD

**Issue by zhuwei** [kkbin505/Arduino-Transmitter-for-ELRS#2]
esp系列没有analogReference(EXTERNAL);
删除这个有影响吗？

**Comment by kkbin505** [comment]
这个是因为霍尔摇杆只支持3.3V所以用了外部参考电压给到ADC，配合我的电路板用，用esp32自己接线不需要用到这个。

有人移植了ESP32：
https://github.com/danxdz/simpleTx_esp32

**Comment by zhuwei** [comment]
好的，谢谢。我尝试双工看看
