### ISSUE TITLE
Why not just use ELRS+stick for Transmitter

### ISSUE THREAD

**Issue by hjchjcjh** [kkbin505/Arduino-Transmitter-for-ELRS#3]
It is recommended to integrate all applications into the ELRS, because esp32 has many ADCs and the joystick can be directly connected to the ADC of ESP32,

**Comment by kkbin505** [comment]
That a good suggestion.
The transmitter as it's name is to keep code simple. If integrate all staff in the esp32, the code will be too complex.
Second, simpletx decouple the fast development of the expresslrs repo, the main code of simpletx will be compatabile from expresslrs 1.0 all the way to 2.3 and further. It is easier to maintain. 
If you are looking for directly ADC to expresslrs, you can alway find information in the expresslrs handset repo:
https://github.com/ExpressLRS/ExpressLRS-Hardware
