### ISSUE TITLE
PPM Output?

### ISSUE THREAD

**Issue by TheBellmanHimself** [kkbin505/Arduino-Transmitter-for-ELRS#7]
Unfortunately I have been put in the position where I need to use PPM output from the arduino to a module.  But something doesn't seem to be working.

With PPMOUTPUT defined the flight controller seems to get a partially valid PPM stream with the arduino directly connected, it receives the default positions.  All the aux switch channels seem to work.  But no stick movement is happening.  

Something I missed?  I'm testing on an Uno instead of a nano at the moment, is there some quirk to the interrupt pins between the two?

Thanks

**Comment by kkbin505** [comment]
I do not have a change to test the ppm to FC scenario, but I out put ppm to a usb dongel works fine.
My suggestion is first to test if the adc works fine on your uno, you can open debug mode and out put analoge singal from stick.
Otherwise you need a oscillograph to debug.

**Comment by kkbin505** [comment]
This is not an issue
