### ISSUE TITLE
有个疑问 ，电路图上 arduino TX是直连高频头，高频头用ESP32 输入电平是3.3V； Arduino 输出电平是5V的 这样不会有问题吗？

### ISSUE THREAD

**Issue by geekli** [kkbin505/Arduino-Transmitter-for-ELRS#9]

**Comment by trogalko** [comment]
For ESP32, VCC must 3.3V, but IO is 5V tolerant. Please check here : https://www.qworqs.com/2021/05/19/are-the-esp32-and-esp8266-5v-tolerant-yes-they-officially-are/
